# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant::Config.run do |config|
  config.vm.box = "zendsrv2"
  config.vm.box_url = "http://files.vagrantup.com/precise64.box"

  config.vm.forward_port 80, 8081
  #config.vm.forward_port 10083, 10083
  config.vm.forward_port 10084, 10084

  config.vm.share_folder "v-web-app", "/home/vagrant/app", "../app"

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "chef/cookbooks"
    chef.roles_path = "chef/roles"
    chef.add_role "server"
  end
end
